# Generated by Django 4.0 on 2022-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('img', models.ImageField(null=True, upload_to='brand_imgs')),
                ('img_origin_path', models.CharField(max_length=400, null=True)),
            ],
            options={
                'db_table': 'hype_brand',
            },
        ),
    ]
