# Generated by Django 4.0 on 2022-03-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_cachedb_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingTaskBlogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.SmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('not started', 'not started'), ('in process', 'in process'), ('in transaction', 'in transaction'), ('done', 'done'), ('error', 'error')], max_length=25)),
                ('task_type', models.CharField(choices=[('WEEK', 'week'), ('ONE_TIME', 'one time')], max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(auto_now_add=True)),
                ('blogger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.blogger')),
            ],
            options={
                'db_table': 'main_instagram_parsing_task_blogger',
                'unique_together': {('blogger_id', 'day')},
            },
        ),
        migrations.CreateModel(
            name='ParsingTaskMicroservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not started', 'not started'), ('in process', 'in process'), ('in transaction', 'in transaction'), ('done', 'done'), ('error', 'error')], db_index=True, max_length=25)),
                ('parser_task_id', models.BigIntegerField(db_index=True, default=None, null=True)),
                ('task_type_id', models.SmallIntegerField()),
                ('task_type_name', models.CharField(max_length=25)),
                ('extra_info', models.JSONField(default=None, null=True)),
                ('data', models.JSONField(default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flood.parsingtaskblogger')),
            ],
            options={
                'db_table': 'main_instagram_parsing_task_microservice',
            },
        ),
    ]
