# Generated by Django 4.0 on 2022-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingtaskmicroservice',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
