# Generated by Django 4.0 on 2022-03-30 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_address_latitude_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_tasks', to='main.blogger')),
            ],
            options={
                'db_table': 'hype_task_cron',
            },
        ),
    ]
