# Generated by Django 4.0 on 2022-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial_hype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotion',
            old_name='name',
            new_name='original_name',
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='name',
            new_name='original_name',
        ),
        migrations.RenameField(
            model_name='verificationtype',
            old_name='name',
            new_name='original_name',
        ),
        migrations.AddField(
            model_name='address',
            name='original_city',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='original_country',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emotion',
            name='native_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gender',
            name='native_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='verificationtype',
            name='native_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
