# Generated by Django 4.0 on 2022-03-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_emotion_original_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='original_name',
            new_name='name_1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='original_name_1',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='original_name',
            new_name='name_1',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name',
            new_name='original_name_1',
        ),
    ]
