# Generated by Django 4.0 on 2022-03-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_original_name_category_name_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='original_name_1',
            new_name='original_name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='name_1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='original_name_1',
            new_name='original_name',
        ),
    ]
