# Generated by Django 4.0 on 2022-03-25 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_1_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.CharField(db_index=True, max_length=255)),
                ('data', models.JSONField(default=None, null=True)),
                ('day', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.blogger')),
            ],
            options={
                'db_table': 'hype_rest_cache_db',
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(auto_now_add=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blogger')),
            ],
            options={
                'db_table': 'hype_bloggers_archive',
                'unique_together': {('blogger_id', 'day')},
            },
        ),
    ]
