# Generated by Django 4.0 on 2022-04-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_address_latitude_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.blogger'),
        ),
    ]
