# Generated by Django 4.0 on 2022-04-10 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_post_blogger'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='advertisers_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
