# Generated by Django 4.0 on 2022-04-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blogger_advertisers_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.address'),
        ),
    ]
