# Generated by Django 3.2.9 on 2022-04-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_address_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloggerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_date', models.DateTimeField(auto_created=True)),
                ('followers_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('contents_count', models.IntegerField()),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.blogger')),
            ],
        ),
    ]
